apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-experiments-root-application
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/maas-gitops'
    targetRevision: main
    path: clusters/ocpai3-aws
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    automated:
      enabled: false      # Explicitly disables automated sync
      prune: false        # Don't auto-prune deleted resources
      selfHeal: false     # Don't auto-correct manual cluster changes
    syncOptions:
      - ApplyOutOfSyncOnly=true # 'true' means only apply changes that are out of sync, 'false' means apply all changes
